# Generated by Django 3.2.13 on 2022-11-27 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ['user'], 'verbose_name': 'Аккаунт', 'verbose_name_plural': 'Аккаунты'},
        ),
        migrations.RemoveField(
            model_name='profile',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='twitter',
        ),
        migrations.AddField(
            model_name='profile',
            name='dolgnost',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='profile',
            name='kabinet',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='profile',
            name='telefon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Примечание'),
        ),
    ]
