# Generated by Django 4.2.1 on 2023-06-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyHelicopter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('edesc', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('erem', models.BooleanField(default=False, verbose_name='Удалить?')),
                ('name', models.CharField(default='Валера23', max_length=255, verbose_name='Модель')),
                ('color', models.CharField(default='Черный', max_length=255, verbose_name='Цвет')),
                ('nazn', models.CharField(default='Спасатель', max_length=255, verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Вертолет',
                'verbose_name_plural': 'Вертолеты',
                'ordering': ['id'],
            },
        ),
    ]
