# Generated by Django 4.2.5 on 2023-10-27 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('anketa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sertif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Название')),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Filled_sertif', models.ImageField(blank=True, upload_to='serif/%Y/%m/%d')),
                ('Blank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anketa.blank', verbose_name='Бланк')),
                ('Users', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Сертификат',
                'verbose_name_plural': 'Сертификаты',
                'ordering': ['-title'],
            },
        ),
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=50, verbose_name='Название')),
                ('Score', models.PositiveIntegerField()),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('Skills', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='anketa.skills', verbose_name='Навык')),
                ('Users', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ['-title'],
            },
        ),
    ]
