# Generated by Django 4.2.1 on 2023-12-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testik', '0003_alter_answers_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='score',
            field=models.DecimalField(decimal_places=1, max_digits=1, max_length=5),
        ),
    ]
