# Generated by Django 4.2.1 on 2023-12-18 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testik', '0004_alter_answers_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='score',
            field=models.PositiveIntegerField(max_length=5),
        ),
    ]
