# Generated by Django 4.2.1 on 2023-12-18 11:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testik', '0005_alter_answers_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='score',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)]),
        ),
    ]
